server:
  port: 8085

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092

aws:
  s3:
    endpoint: http://localhost:4566
    bucket-name: ecommerce-invoices
    access-key: ${AWS_ACCESS_KEY:test}
    secret-key: ${AWS_SECRET_KEY:test}
    region: us-east-1
